apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag.fullname" . }}-config
  labels:
    {{- include "rag.labels" . | nindent 4 }}
data:
  OLLAMA_HOST: {{ .Values.backend.env.ollamaHost | quote }}
  VECTOR_DB_PATH: {{ .Values.backend.env.vectorDbPath | quote }}
  PROJECT_NAME: "RAG Research Assistant"
  VERSION: {{ .Chart.AppVersion | quote }}
