apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag.fullname" . }}-backend-service
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: {{ include "rag.name" . }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag.fullname" . }}-frontend-service
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: {{ include "rag.name" . }}-frontend
---
{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rag-ollama-service # Must match values.yaml connection string
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: 11434
      protocol: TCP
      name: ollama
  selector:
    app: {{ include "rag.name" . }}-ollama
{{- end }}
