apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-ingress
  namespace: rag-namespace
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: rag-assistant-tls
      hosts:
        - rag-api.local
        - rag-app.local
  rules:
    - host: rag-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-backend-service
                port:
                  number: 8001
    - host: rag-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-frontend-service
                port:
                  number: 8501
